name: acl23doc2dial
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asttokens=2.2.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - blas=2.116
  - blas-devel=3.9.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - cffi=1.15.1
  - charset-normalizer=3.1.0
  - click=8.1.3
  - comm=0.1.3
  - cudatoolkit=11.8.0
  - dataclasses=0.8
  - debugpy=1.6.7
  - decorator=5.1.1
  - entrypoints=0.4
  - executing=1.2.0
  - faiss=1.7.2
  - faiss-gpu=1.7.2
  - fftw=3.3.10
  - filelock=3.12.0
  - gmp=6.2.1
  - gmpy2=2.1.2
  - huggingface_hub=0.13.4
  - icu=70.1
  - idna=3.4
  - importlib-metadata=6.4.1
  - ipykernel=6.23.1
  - ipython=8.13.2
  - jedi=0.18.2
  - jinja2=3.1.2
  - joblib=1.1.1
  - jupyter_client=7.4.9
  - jupyter_core=5.3.0
  - ld_impl_linux-64=2.40
  - libblas=3.9.0
  - libcblas=3.9.0
  - libfaiss=1.7.2
  - libfaiss-avx2=1.7.2
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libhwloc=2.8.0
  - libiconv=1.17
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnsl=2.0.0
  - libopenblas=0.3.21
  - libprotobuf=3.21.12
  - libsodium=1.0.18
  - libstdcxx-ng=12.2.0
  - libuuid=2.38.1
  - libxml2=2.9.14
  - libzlib=1.2.13
  - llvm-openmp=16.0.1
  - lz4-c=1.9.4
  - markupsafe=2.1.2
  - matplotlib-inline=0.1.6
  - mkl=2022.2.1
  - mpc=1.3.1
  - mpfr=4.2.0
  - mpmath=1.3.0
  - ncurses=6.3
  - nest-asyncio=1.5.6
  - networkx=3.1
  - openblas=0.3.21
  - openssl=3.1.0
  - packaging=23.1
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.0.1
  - platformdirs=3.5.1
  - prompt-toolkit=3.0.38
  - prompt_toolkit=3.0.38
  - psutil=5.9.5
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.15.1
  - pyopenssl=23.1.1
  - pysocks=1.7.1
  - python=3.10.4
  - python-dateutil=2.8.2
  - python_abi=3.10
  - pytorch=2.0.0
  - pyyaml=6.0
  - pyzmq=25.0.2
  - readline=8.2
  - regex=2023.3.23
  - requests=2.28.2
  - sacremoses=0.0.53
  - scikit-learn=1.2.2
  - six=1.16.0
  - sleef=3.5.1
  - sqlite=3.39.2
  - stack_data=0.6.2
  - sympy=1.11.1
  - tbb=2021.7.0
  - threadpoolctl=3.1.0
  - tk=8.6.12
  - tokenizers=0.10.3
  - tornado=6.3.2
  - traitlets=5.9.0
  - transformers=4.10.0
  - typing-extensions=4.5.0
  - typing_extensions=4.5.0
  - urllib3=1.26.15
  - wcwidth=0.2.6
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.15.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - addict==2.4.0
      - aiohttp==3.8.4
      - aiosignal==1.3.1
      - aliyun-python-sdk-core==2.13.36
      - aliyun-python-sdk-kms==2.16.0
      - async-timeout==4.0.2
      - attrs==22.2.0
      - certifi==2022.12.7
      - cmake==3.26.3
      - colorama==0.4.6
      - contourpy==1.0.7
      - crcmod==1.7
      - cryptography==40.0.1
      - cycler==0.11.0
      - datasets==2.8.0
      - dill==0.3.6
      - einops==0.6.0
      - fastjsonschema==2.17.1
      - fonttools==4.39.3
      - frozenlist==1.3.3
      - fsspec==2023.4.0
      - gast==0.5.3
      - jmespath==0.10.0
      - jsonplus==0.8.0
      - jsonschema==4.17.3
      - kiwisolver==1.4.4
      - lit==16.0.1
      - lxml==4.9.2
      - matplotlib==3.7.1
      - multidict==6.0.4
      - multiprocess==0.70.14
      - nbformat==5.8.0
      - numpy==1.24.3
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - oss2==2.17.0
      - pandas==2.0.0
      - pigar==2.0.6
      - pillow==9.5.0
      - portalocker==2.7.0
      - pudb==2022.1.3
      - pyarrow==11.0.0
      - pycryptodome==3.17
      - pyparsing==3.0.9
      - pyrsistent==0.19.3
      - pytz==2023.3
      - responses==0.18.0
      - rouge==1.0.1
      - sacrebleu==2.2.1
      - scipy==1.10.1
      - seaborn==0.12.2
      - sentencepiece==0.1.95
      - setuptools==67.7.2
      - simplejson==3.19.1
      - sortedcontainers==2.4.0
      - tabulate==0.9.0
      - torch-summary==1.4.5
      - torchaudio==2.0.1
      - torchvision==0.15.1
      - tqdm==4.65.0
      - triton==2.0.0
      - tzdata==2023.3
      - ujson==5.7.0
      - urwid==2.1.2
      - urwid-readline==0.13
      - wheel==0.40.0
      - xxhash==3.2.0
      - yapf==0.32.0
      - yarl==1.8.2
